# The URL the site will be built for
base_url = "https://giammanco.me"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zola-theme-terminimal"
title = "Salvatore Giammanco"



[extra]
author = "Salvatore Giammanco"
logo_text = "Salvatore Giammanco"
menu_items = [
    {name = "home", url = "$BASE_URL"},
    {name = "blog", url = "$BASE_URL/blog"},
    {name = "tech blog", url = "$BASE_URL/techblog"},
    {name = "tech talks", url = "$BASE_URL/techtalks"},
    {name = "projects", url = "$BASE_URL/projects"},
    {name = "contacts", url = "$BASE_URL/content/contact-me"},
    {name = "github", url = "https://github.com/salvatore-giammanco", newtab = true},
]